version: "3.4"

networks:
  litkey-net:

services:
  mysqlserver:
    image: mariadb:10
    environment:
      # diese Variablen aktualisieren
      - MYSQL_DATABASE='litkey'
      - MYSQL_PORT='3306'
      - MYSQL_USER='litkeyuser'
      - MYSQL_PASSWORD=${DBPASS}
      - MYSQL_RANDOM_ROOT_PASSWORD=true
    command: ["--character-set-server=utf8", "--collation-server=utf8_bin"]
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-p${MYSQL_PASSWORD}",
          "-u${MYSQL_USER}",
        ]
      interval: 20s
      timeout: 10s
      retries: 10
    networks:
      litkey-net:

  webserver:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    image: litkeyweb:1.0
    environment:
      - DBPASS=${DBPASS}
    ports:
      - "8555:8000"
    depends_on:
      mysqlserver:
        condition: service_healthy
    mem_limit: 1g
    memswap_limit: 1g
    restart: unless-stopped
    networks:
      litkey-net:
